/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_autch_android_bouncetest_FluidBallsThread */

#ifndef _Included_net_autch_android_bouncetest_FluidBallsThread
#define _Included_net_autch_android_bouncetest_FluidBallsThread
#ifdef __cplusplus
extern "C" {
#endif
#undef net_autch_android_bouncetest_FluidBallsThread_MIN_PRIORITY
#define net_autch_android_bouncetest_FluidBallsThread_MIN_PRIORITY 1L
#undef net_autch_android_bouncetest_FluidBallsThread_NORM_PRIORITY
#define net_autch_android_bouncetest_FluidBallsThread_NORM_PRIORITY 5L
#undef net_autch_android_bouncetest_FluidBallsThread_MAX_PRIORITY
#define net_autch_android_bouncetest_FluidBallsThread_MAX_PRIORITY 10L
#undef net_autch_android_bouncetest_FluidBallsThread_FPS
#define net_autch_android_bouncetest_FluidBallsThread_FPS 30L
/*
 * Class:     net_autch_android_bouncetest_FluidBallsThread
 * Method:    fluidballs_init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_autch_android_bouncetest_FluidBallsThread_fluidballs_1init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_autch_android_bouncetest_FluidBallsThread
 * Method:    fluidballs_exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_bouncetest_FluidBallsThread_fluidballs_1exit
  (JNIEnv *, jobject);

/*
 * Class:     net_autch_android_bouncetest_FluidBallsThread
 * Method:    fluidballs_setaccel
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_net_autch_android_bouncetest_FluidBallsThread_fluidballs_1setaccel
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     net_autch_android_bouncetest_FluidBallsThread
 * Method:    fluidballs_drawballs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_bouncetest_FluidBallsThread_fluidballs_1drawballs
  (JNIEnv *, jobject);

/*
 * Class:     net_autch_android_bouncetest_FluidBallsThread
 * Method:    fluidballs_update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_bouncetest_FluidBallsThread_fluidballs_1update
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
